resources:
  - url: http://127.0.0.1:5000/washing-machine-card.js
    type: module
views:
  - cards:
      - type: custom:washing-machine-card
        name: Washing Machine Card Development
        entity: sun.sun
        test_gui: true
